Token authorization
antonina18/shop-online-app pull request #2
Opened 2020-01-19 11:34 UTC by AJurczyk

2020-01-31 07:01 UTC, antonina18 requested changes

2020-01-31 07:01 UTC, antonina18 commented on pom.xml
> +            <version>2.2.2.RELEASE</version>
please keep versions in properties.

2020-01-31 07:01 UTC, antonina18 commented on pom.xml
> +
empty line

2020-01-31 07:01 UTC, antonina18 commented on src/main/java/pl/pongut/shop/Main.java
> +    @Bean
Why it's here? Main it's not a good place to create bean.

2020-01-31 07:01 UTC, antonina18 commented on src/main/java/pl/pongut/shop/config/DatabaseInitializer.java
> +//        String encodedPassword = passwordEncoder.encode("kotu123");
You shouldn't commit commented line

2020-01-31 07:01 UTC, antonina18 commented on src/main/java/pl/pongut/shop/security/JwtAuthorizationFilter.java
> +        if (header == null || !header.startsWith(jwtConfig.getTokenPrefix())) {
It's good practice to make it one line method, where name means something
!header.startsWith(jwtConfig.getTokenPrefix()) < can be replaced "hasTokenPrefix" for example

2020-01-31 07:01 UTC, antonina18 commented on src/main/java/pl/pongut/shop/security/WebSecurityConfig.java
> +                .antMatchers("/api/public", "/login").permitAll()
please make these two strings constant

2020-01-31 07:01 UTC, antonina18 commented on src/main/java/pl/pongut/shop/service/UserService.java
> +                .map(u -> new org.springframework.security.core.userdetails.User(
org.springframework.security.core.userdetails. why it's here?

2020-01-31 07:01 UTC, antonina18 commented on src/main/java/pl/pongut/shop/service/UserService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found with username: " + username));
User not found with username: > Username x not found?

2020-02-23 15:47 UTC, ajurczyk1 commented on pom.xml
> +            <version>2.2.2.RELEASE</version>
done

2020-02-23 15:50 UTC, antonina18 approved these changes

2020-02-23 15:51 UTC, merged